# **EZRecords Package**



## Overview
EZRecords is a package built on R(3.3.2) which aims to streamline the bookkeeping and stock management for retail/reselling businesses. Users can either utilize the stapled application, [EZRecords APP](https://samantheluidatascience.shinyapps.io/EZRecords_App_Demo/), or suit themselves with the functionality offered by the package at the backend.

The following shows the classes and their methods:

* Class __*single_item*__ : an S4 class representing an item in an order from a business owner's perspective

 |single_item(category, descrp, model, quant, price, discount, amount, sample, 
  sampling)|

    | __Method__         | __Function__                                                                           |
    |--------------------|-----------------------------------------------------------------------|
    | amount(obj, ...)   | calculate the value of the item|
    | discount(obj, ...) | calculate the remaining fraction of a value after it is discounted|
    | is_empty(obj)      | check if the object has only trivial slots|
    | print(obj, ...)    | siliently return a representation of the object as a character string|


* Class __*all_items*__ : an S4 class representing all of the items in an order from a business owner's perspective

    | __Method__         | __Function__                                                                           |
    |--------------------|----------------------------------------------------------------------------------------|
    | add(obj, item, ...)| appends an item to athe list _items_ 
    | amount(obj, ...)   | calculate the total amount of all of the items in the _items_ list of the object|                             
    | display(obj, ...)| show the content of the object in a more viewer-friendly format |
    | is_empty(obj)      | check if the object has only trivial slots     |
    | print(obj, ...)    | siliently return a representation of the object as a character string                 |
    |remove_last(obj, ...)|remove the most recently added item from the _items_ list of the object|


* Class __*product_transac*__ : an S4 class representing a transaction record of an order in a business transaction log

    | __Method__         | __Function__                                                                           |
    |--------------------|-----------------------------------------------------------------------|
    | is_empty(obj)      | check if the object has only trivial slots|
    | print(obj, ...)    | siliently return a representation of the object as a data frame|


* Class __*product_logs*__ : an S4 class representing a business transaction log

    | __Method__         | __Function__                                                                           |
    |--------------------|----------------------------------------------------------------------------------------|
    | add(obj, item, ...)| appends an item to athe list _logs_ |
    | find_duplicate(obj, date, orn, sup, ...)| check if an order number has a duplicate in the database and return the location of the duplicate if one exists |
    | is_empty(obj)      | check if the object has only trivial slots     |
    |join(obj, another, ...)| append another log to the calling object and return a new _product_logs_ object with the combined logs |
    | order_track(obj, ...) | create a new code for the order number for each transaction in the log |
    | print(obj, ...)    | siliently return a representation of the object as a data frame |                 |
    |show_all_items_info(obj, ...)| extract information about each transaction including the date, type, category, and model inside the log for later summary |
    | show_duplicate(obj, date, orn, sup, ...) | display the existing record of transaction in the log who has the same order number as the one entered by the user |
    | show_stock(obj, ...) |  extract the pertinent items' information for each item from each transaction record of the business log for further calculation of the stock status |
    
    
* Class __*invoice*__ : an S4 class which handles order number generation and keeps the order numbers in a tracking system

    | __Method__         | __Function__                                                                           |
    |--------------------|----------------------------------------------------------------------------------------|
    | invoice(obj, is_sampling)| generate an order number for the transaction when a sale is made |
